<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [
<!-- this is a fake DTD -->
<!ELEMENT SystemDefinition (systemModel?, build?)>
<!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED
>
<!-- all paths are relative to the root of the source -->

<!-- System Model Section of DTD -->
<!ELEMENT systemModel (layer+)>

<!ELEMENT layer (logicalset* | module*)*>
<!-- Kernel Services, Base Services, OS Services, Etc -->
<!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  silly CDATA #IMPLIED
  span CDATA #IMPLIED
  align (left | right | center) #IMPLIED
>

<!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!-- Generic OS services, Comms Services, etc -->
<!ATTLIST logicalset 
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
>

<!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
<!-- Telephony services, Networking Services, etc -->
<!ATTLIST logicalsubset 
  name CDATA #REQUIRED
>

<!ELEMENT module (component* | unit* | package* | prebuilt*)*>
<!-- Screen Driver, Content Handling, etc -->
<!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED  
>

<!ELEMENT component (unit* | package* | prebuilt*)*>
<!-- units or packages -->
<!ATTLIST component
  name CDATA #REQUIRED
  did CDATA #IMPLIED
>

<!ELEMENT unit EMPTY >
<!-- must be buildable (bld.inf) -->
<!-- bldFile will soon be removed in favour of mrp -->
<!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED
>

<!ELEMENT package EMPTY >
<!-- like a unit, but not buildable -->
<!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED
>

<!ELEMENT prebuilt EMPTY>
<!-- pre-built CBR component -->
<!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED
>



<!-- Build Section of DTD -->
<!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>

<!ELEMENT unitList (unitRef+)>
<!-- e.g. common, beech, cedar, etc -->
<!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED
>

<!ELEMENT unitRef EMPTY>
<!-- Reference to unit in System Model -->
<!ATTLIST unitRef
  unit IDREF #REQUIRED
>

<!ELEMENT targetList EMPTY>
<!-- e.g. DEFAULT_7.0S, TOOLS_7.0S, etc -->
<!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED
>

<!ELEMENT target EMPTY>
<!-- e.g. WINS, WINSCW, ARM4, etc -->
<!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED
>

<!ELEMENT option EMPTY>
<!-- e.g. Keepgoing, SaveSpace, etc -->
<!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED
>

<!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
<!-- 7.0s, 8.0a, 8.0b, cuskit, etc -->
<!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED
>
<!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>

<!ELEMENT unitListRef EMPTY>
<!-- Reference to unitList -->
<!ATTLIST unitListRef
  unitList IDREF #REQUIRED
>

<!ELEMENT layerRef EMPTY>
<!-- Reference to named entity in the model, usually a layer -->
<!ATTLIST layerRef
  layerName CDATA #REQUIRED
>

<!ELEMENT buildLayer EMPTY>
<!-- bldmake, abld export, etc -->
<!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED
>

<!ELEMENT specialInstructions EMPTY>
<!-- BootStrap -->
<!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED
>

]>

<SystemDefinition name="MCL" schema="1.4.0">
  
  <systemModel>
    <layer name="Tools and Utils and SDKENG" levels="tools sdk">
      <module name="Tools and Utils" level="tools">
        <component name="BUILDSYSTEMTOOLS">
          <unit unitID="BUILDSYSTEMTOOLS" name="tools_build" bldFile="common\generic\tools\build\group" mrp="common\generic\tools\build\group\tools_build.mrp"/>
          <package name="gt_techview_baseline" mrp="common\generic\tools\cbr\mrpfiles\gt_techview_baseline.mrp"/>
		  <!-- DEF087736 This is needed for generating export tables but shouldn't appear otherwise it is included in techview and gt
		     <package name="gt_only_baseline" mrp="common\generic\tools\cbr\mrpfiles\gt_only_baseline.mrp"/> -->
          <package name="tools_utils_cedar" mrp="cedar\generic\utils\tools_utils_cedar.mrp"/>
          <package name="tools_utils_common" mrp="common\generic\utils\tools_utils_common.mrp"/>
          <package name="additional_unknown" mrp="common\generic\tools\cbr\mrpfiles\additional_unknown_cedar.mrp"/>
        </component>
        <component name="BCCOMPARATOR">
          <unit unitID="BCCOMPARATOR" name="testtools_cts_Bccomparator" bldFile="Common\testtools\CTS\BCComparator\Group" mrp="common\testtools\CTS\BCComparator\Group\testtools_cts_Bccomparator.mrp"/>
          <package name="testtools_cts_functionalitycheckers" mrp="common\testtools\cts\functionalitycheckers\group\testtools_cts_functionalitycheckers.mrp"/>
        </component>
        <component name="BURTESTSERVER">
          <unit unitID="BURTESTSERVER" name="testtools_burtestserver" bldFile="common\testtools\burtestserver\Group" mrp="common\testtools\burtestserver\group\testtools_burtestserver.mrp"/>
        </component>        
        <component name="CBRTOOLS">
          <unit unitID="CBRTOOLS" name="tools_cbr_tools" bldFile="common\generic\tools\cbr\tools\Group" mrp="common\generic\tools\cbr\tools\group\tools_cbr_tools.mrp" filter="gt"/>
          <unit unitID="CBRPRF" name="tools_cbr_prf" bldFile="common\generic\tools\cbr\prf\group" mrp="common\generic\tools\cbr\prf\group\tools_cbr_prf.mrp"/>
        </component>
        <component name="CDB">
          <unit unitID="CDB" name="testtools_cdb" bldFile="common\testtools\cdb\group" mrp="common\testtools\cdb\group\testtools_cdb.mrp"/>
        </component>
        <component name="CHATSCRIPTS">
          <unit unitID="CHATSCRIPTS" name="ChatScripts" bldFile="common\testtools\ChatScripts\group" mrp="common\testtools\chatscripts\group\testtools_chatscripts.mrp"/>
        </component>
        <component name="DEPCHECK">
          <unit unitID="DEPCHECK" name="tools_depcheck" bldFile="common\generic\tools\depcheck" mrp="common\generic\tools\depcheck\tools_depcheck.mrp"/>
        </component>
        <component name="DEPMODEL">
          <unit unitID="DEPMODEL" name="tools_depmodel" bldFile="common\generic\tools\depmodel\group" mrp="common\generic\tools\depmodel\tools_depmodel.mrp"/>
        </component>
        <component name="DEVELOPERLIBRARY">
          <unit unitID="DEVELOPERLIBRARY_9.3" name="DEVELOPERLIBRARY_9.3" bldFile="common\DEVELOPERLIBRARY\GROUP\devlib93" mrp="common\developerlibrary\group\devlib93\developerlibrary_doc_html.mrp"/>
          <unit unitID="DEVELOPERLIBRARY_SOURCE" name="DEVELOPERLIBRARY_SOURCE" bldFile="common\DEVELOPERLIBRARY\SECURITYSUPPLEMENT\DOC_SOURCE" mrp="common\developerlibrary\developerlibrary_doc_source.mrp" filter="gt"/>
          <package name="developerlibrary_doc_plain_html" mrp="common\developerlibrary\group\devlib93\developerlibrary_doc_plain_html.mrp"/>
          <!-- lots of subsystem documentation packages -->
          <package name="app-engines_documentation" mrp="common\generic\app-engines\documentation\app-engines_documentation.mrp"/>
          <package name="app-framework_confidential" mrp="common\generic\app-framework\confidential\app-framework_confidential.mrp"/>
          <package name="app-framework_documentation" mrp="common\generic\app-framework\documentation\app-framework_documentation.mrp"/>
          <package name="app-services_documentation" mrp="common\generic\app-services\documentation\app-services_documentation.mrp"/>
          <package name="base_documentation" mrp="cedar\generic\base\documentation\base_documentation.mrp"/>
          <package name="comms-infras_documentation" mrp="common\generic\comms-infras\documentation\comms-infras_documentation.mrp"/>
          <package name="comms-infras_extra" mrp="common\generic\comms-infras\comms-infras_extra.mrp"/>
          <package name="graphics_documentation" contract="Symbian_Affiliate"  mrp="common\generic\graphics\documentation\graphics_documentation.mrp"/>
          <package name="networking_documentation" mrp="common\generic\networking\documentation\networking_documentation.mrp"/>
          <package name="security_documentation" mrp="common\generic\security\documentation\security_documentation.mrp"/>
          <package name="ser-comms_documentation" mrp="common\generic\ser-comms\documentation\ser-comms_documentation.mrp"/>
          <package name="syslibs_documentation" mrp="common\generic\syslibs\documentation\syslibs_documentation.mrp"/>
          <package name="system" mrp="common\system\group\system.mrp"/>
          <package name="telephony_confidential" mrp="common\generic\telephony\confidential\telephony_confidential.mrp"/>
          <package name="telephony_documentation" mrp="common\generic\telephony\documentation\telephony_documentation.mrp"/>
          <package name="tools_documentation" mrp="cedar\generic\tools\documentation\tools_documentation.mrp"/>
        </component>
        <component name="E32TOOLS EKA2">
          <unit unitID="E32TOOLS_EKA2" name="tools_e32tools" bldFile="cedar\generic\TOOLS\E32Tools\GROUP" mrp="cedar\generic\tools\e32tools\group\tools_e32tools.mrp"/>
          <package name="tools_e32toolp" mrp="cedar\generic\tools\e32toolp\group\tools_e32toolp.mrp"/>
        </component>
        <component name="EVALID">
          <unit unitID="EVALID" name="tools_evalid" bldFile="common\generic\tools\host_utilities\evalid" mrp="common\generic\tools\host_utilities\evalid\tools_evalid.mrp"/>
        </component>
        <component name="KITCOMPARATOR">
          <unit unitID="KITCOMPARATOR" name="testtools_cts_kitcomparator" bldFile="Common\testtools\CTS\KitComparator\Group" mrp="common\testtools\CTS\KitComparator\group\testtools_cts_kitcomparator.mrp"/>
        </component>
        <component name="PLATTEST">
          <unit unitID="PLATTEST" name="plattest" bldFile="common\generic\plattest\Group" mrp="common\generic\plattest\Group\plattest_tools.mrp" filter="techview"/>
        </component>
        <component name="LEAVESCAN">
          <unit unitID="LEAVESCAN" name="testtools_leavescan" bldFile="common\TestTools\LEAVESCAN\GROUP" mrp="common\testtools\Leavescan\group\testtools_leavescan.mrp"/>
        </component>
        <component name="PROGRAMCHECKER">
          <unit unitID="PROGRAMCHECKER" name="testtools_programchecker" bldFile="common\testtools\ProgramChecker\Group" mrp="common\testtools\ProgramChecker\group\testtools_programchecker.mrp"/>
        </component>
        <component name="RCOMP">
          <unit unitID="RCOMP" name="tools_rcomp" bldFile="common\generic\TOOLS\RCOMP\GROUP" mrp="common\generic\tools\rcomp\group\tools_rcomp.mrp"/>
        </component>
        <component name="REDISTRIBUTION">
          <unit unitID="REDISTRIBUTION" name="tools_redistribution_common" bldFile="common\generic\TOOLS\REDISTRIBUTION" mrp="common\generic\tools\redistribution\tools_redistribution_common.mrp" filter="gt"/>
          <package name="tools_redistribution_winc" mrp="cedar\generic\tools\redistribution\tools_redistribution_winc.mrp"/>
          <package name="additional_tools" mrp="common\generic\tools\redistribution\additional_tools.mrp"/>
        </component>      
        <component name="RESOURCE_HANDLER">
          <package name="testtools_resourcehandler_gt" contract="Symbian_Affiliate"  mrp="common\testtools\resourcehandler\tvresourcehandler\group\testtools_resourcehandler_gt.mrp"/>
        </component>
        <component name="ROMKIT_EKA2">
          <unit unitID="ROMKIT_EKA2" name="tools_romkit" bldFile="cedar\generic\TOOLS\ROMKIT\GROUP" mrp="cedar\generic\tools\romkit\group\tools_romkit.mrp"/>
        </component>
        <component name="MIGRATIONTOOL">
          <unit unitID="MIGRATIONTOOL" name="testtools_migrationtool" bldFile="common\testtools\migrationtool\group" mrp="common\testtools\migrationtool\group\testtools_migrationtool.mrp"/>
        </component>
        <component name="TESTDRIVER">
          <unit unitID="TESTDRIVER" name="testtools_testdriver" bldFile="common\testtools\TestDriver\Group" mrp="common\testtools\TestDriver\Group\testtools_testdriver.mrp"/>
        </component>
        <component name="SMOKETEST">
          <unit unitID="SMOKETEST" name="testtools_smoketest" bldFile="common\testtools\smoketest\GROUP" mrp="common\testtools\Smoketest\Group\testtools_smoketest.mrp" filter="gt"/>
        </component>
        <component name="STATAPI">
          <unit unitID="STATAPI" name="testtools_stat_device_gt" bldFile="common\testtools\STAT\device\source\statapi\console" mrp="common\testtools\stat\device\group\testtools_stat_device_gt.mrp" filter="gt"/>
          <package name="testtools_stat_common_source" contract="Symbian_Affiliate"  mrp="common\testtools\stat\group\testtools_stat_common_source.mrp" filter="gt"/>
        </component>
        <component name="STAT_DESKTOP">
          <unit unitID="STAT_DESKTOP" name="testtools_stat_desktop" contract="Symbian_Affiliate"  bldFile="common\testtools\stat\desktop\group" mrp="common\testtools\stat\desktop\group\testtools_stat_desktop.mrp" filter="gt"/>
        </component>
        <component name="Bluetooth Logger">
            <unit unitID="BLUETOOTH_LOGGER" name="bluetooth_logger" bldFile="common\generic\bluetooth\latest\bluetooth\logger\group" mrp="common\generic\bluetooth\latest\bluetooth\logger\group\bluetooth_logger.mrp"/>
          </component>
        <component name="TESTEXECUTE">
          <unit unitID="TESTEXECUTE" name="tools_testexecute" bldFile="common\TestTools\TESTEXECUTE\GROUP" mrp="common\testtools\testexecute\Group\tools_testexecute.mrp"/>
        </component>
        <component name="TESTTOOLS_DESKTOP">
          <unit unitID="TESTTOOLS_DESKTOP" name="testtools_desktop" bldFile="common\TestTools\desktop\GROUP" mrp="common\testtools\desktop\Group\testtools_desktop.mrp" filter="gt"/>
          <package name="testtools_wintunnel" mrp="common\testtools\wintunnel\group\testtools_wintunnel_srconly.mrp"/>
        </component>
        <component name="Use Case Controller">
          <unit unitID="TESTTOOLS_UCC" name="testtools_ucc" bldFile="common\TestTools\UCC\BuildScripts\GROUP" mrp="common\TestTools\UCC\BuildScripts\GROUP\testtools_ucc.mrp"/>
        </component>
        <component name="CINIDATA">
          <unit unitID="CINIDATA" name="tools_cinidata" bldFile="common\generic\TOOLS\CINIDATA" mrp="common\generic\tools\cinidata\tools_cinidata.mrp"/>
        </component>
        <component name="AUTOTEST">
          <unit unitID="AUTOTEST" name="tools_autotest" bldFile="common\generic\TOOLS\AUTOTEST\GROUP" mrp="common\generic\tools\autotest\group\tools_autotest.mrp"/>
        </component>
        <component name="TESTCONFIGFILEPARSER">
          <unit unitID="TESTCONFIGFILEPARSER" name="tools_testconfigfileparser" bldFile="common\generic\TOOLS\testconfigfileparser\GROUP" mrp="common\generic\tools\testconfigfileparser\group\tools_testconfigfileparser.mrp"/>
        </component>
        <component name="KITSETUPAPP">
          <unit unitID="KITSETUPAPP" name="tools_devkits_kitsetupapp" bldFile="common\generic\TOOLS\DevKits\KitSetupApp\group" mrp="common\generic\tools\devkits\KitSetupApp\group\tools_devkits_kitsetupapp.mrp" filter="gt" priority="1020"/>
        </component>
        <component name="NAVIGATION_PAGES">
          <package name="tools_sdk_eng_navigationpages" mrp="common\generic\tools\sdk_eng\navigationpages\tools_sdk_eng_navigationpages.mrp"/>
        </component>
        <component name="PRODUCTINSTALLER">
          <unit unitID="PRODUCTINSTALLER" name="tools_custkits_productinstaller" bldFile="common\generic\TOOLS\Custkits\ProductInstaller\group" mrp="common\generic\TOOLS\Custkits\ProductInstaller\group\tools_custkits_productinstaller.mrp" filter="gt"/>
        </component>
        <component name="REDISTRIBUTION_WINC_EKA2">
          <unit unitID="REDISTRIBUTION_WINC_EKA2" name="tools_redistribution_cedar" bldFile="cedar\generic\tools\redistribution" mrp="cedar\generic\tools\redistribution\tools_redistribution_cedar.mrp"/>
        </component>
        <component name="MAKEKEYS">
          <unit unitID="MAKEKEYS" name="security_makekeys" bldFile="common\generic\SECURITY\MakeKeys\GROUP" mrp="common\generic\security\makekeys\group\security_makekeys.mrp" filter="gt"/>
        </component>
        <component name="CAPTOOLS">
          <unit unitID="CAPTOOLS" name="testtools_captools" bldFile="common\testtools\captools\group" mrp="common\testtools\CapTools\group\testtools_captools.mrp"/>
        </component>
        <component name="Packet Loopback CSY">
          <unit unitID="PACKETLOOPBACKCSY" name="PacketLoopbackCSY" bldFile="common\generic\networking\test\PacketLoopbackCSY\group" mrp="common\generic\networking\test\PacketLoopbackCSY\group\PacketLoopbackCSY.mrp"/>
        </component>
        <component name="Graphics Utilities">
          <unit unitID="MemSpy" name="graphics_memspy" bldFile="common\generic\graphics\testutils\memspy\group" mrp="common\generic\graphics\testutils\memspy\group\graphics_memspy.mrp" filter="techview" /> 
        </component>
        <component did="done" name="UTRACE">
          <unit unitID="UTRACE_API" name="testtools_utrace_api" bldFile="common\testtools\trace\utrace\api\group" mrp="common\testtools\trace\utrace\api\group\testtools_utrace_api.mrp"/>
        </component>
      </module>
      <module name="SDKENG" level="sdk">
        <component name="RUNPERL">
          <unit unitID="RUNPERL" name="tools_sdk_eng_runperl" bldFile="common\generic\TOOLS\SDK_ENG\RUNPERL\GROUP" mrp="common\generic\tools\sdk_eng\runperl\group\tools_sdk_eng_runperl.mrp" filter="gt"/>
        </component>
        <component name="BUILD-TOOLS">
          <unit unitID="BUILD-TOOLS" name="tools_sdk_eng_build-tools" bldFile="common\generic\TOOLS\SDK_ENG\BUILD-TOOLS\GROUP" mrp="common\generic\tools\sdk_eng\build-tools\group\tools_sdk_eng_build-tools.mrp" filter="gt"/>
        </component>
        <component name="JAVALIBRARY">
          <unit unitID="JAVALIBRARY" name="tools_sdk_eng_javalibrary" bldFile="common\generic\TOOLS\SDK_ENG\JAVALIBRARY\GROUP" mrp="common\generic\tools\sdk_eng\javalibrary\group\tools_sdk_eng_javalibrary.mrp" filter="gt"/>
        </component>
        <component name="ASSERTION">
          <unit unitID="ASSERTION" name="tools_sdk_eng_assertion" bldFile="common\generic\TOOLS\SDK_ENG\ASSERTION\GROUP" mrp="common\generic\tools\sdk_eng\assertion\group\tools_sdk_eng_assertion.mrp" filter="gt"/>
        </component>
        <component name="ENUM">
          <unit unitID="ENUM" name="tools_sdk_eng_enum" bldFile="common\generic\TOOLS\SDK_ENG\ENUM\GROUP" mrp="common\generic\tools\sdk_eng\enum\group\tools_sdk_eng_enum.mrp" filter="gt"/>
        </component>
        <component name="LOGGER">
          <unit unitID="LOGGER" name="tools_sdk_eng_logger" bldFile="common\generic\TOOLS\SDK_ENG\LOGGER\GROUP" mrp="common\generic\tools\sdk_eng\logger\group\tools_sdk_eng_logger.mrp" filter="gt"/>
        </component>
        <component name="FILESYS">
          <unit unitID="FILESYS" name="tools_sdk_eng_filesys" bldFile="common\generic\TOOLS\SDK_ENG\FILESYS\GROUP" mrp="common\generic\tools\sdk_eng\filesys\group\tools_sdk_eng_filesys.mrp" filter="gt"/>
        </component>
        <component name="ENVVAR">
          <unit unitID="ENVVAR" name="tools_sdk_eng_envvar" bldFile="common\generic\TOOLS\SDK_ENG\ENVVAR\GROUP" mrp="common\generic\tools\sdk_eng\envvar\group\tools_sdk_eng_envvar.mrp" filter="gt"/>
        </component>
        <component name="INSTALLUTILS">
          <unit unitID="INSTALLUTILS" name="tools_sdk_eng_installutils" bldFile="common\generic\TOOLS\SDK_ENG\INSTALLUTILS\GROUP" mrp="common\generic\tools\sdk_eng\InstallUtils\group\tools_sdk_eng_installutils.mrp" filter="gt"/>
        </component>
        <component name="MNEMONICFIX">
          <unit unitID="MNEMONICFIX" name="tools_sdk_eng_mnemonicfix" bldFile="common\generic\TOOLS\SDK_ENG\MNEMONICFIX\GROUP" mrp="common\generic\tools\sdk_eng\mnemonicfix\group\tools_sdk_eng_mnemonicfix.mrp" filter="gt"/>
        </component>
        <component name="PATHBROWSER">
          <unit unitID="PATHBROWSER" name="tools_sdk_eng_pathbrowser" bldFile="common\generic\TOOLS\SDK_ENG\PATHBROWSER\GROUP" mrp="common\generic\tools\sdk_eng\pathbrowser\group\tools_sdk_eng_pathbrowser.mrp" filter="gt"/>
        </component>
        <component name="SHELLEXEC">
          <unit unitID="SHELLEXEC" name="tools_sdk_eng_shellexec" bldFile="common\generic\TOOLS\SDK_ENG\SHELLEXEC\GROUP" mrp="common\generic\tools\sdk_eng\shellexec\group\tools_sdk_eng_shellexec.mrp" filter="gt"/>
        </component>
        <component name="SWINGWORKER">
          <unit unitID="SWINGWORKER" name="tools_sdk_eng_swingworker" bldFile="common\generic\TOOLS\SDK_ENG\SWINGWORKER\GROUP" mrp="common\generic\tools\sdk_eng\swingworker\group\tools_sdk_eng_swingworker.mrp" filter="gt"/>
        </component>
        <component name="TESTCASERUNNER">
          <unit unitID="TESTCASERUNNER" name="tools_sdk_eng_testcaserunner" bldFile="common\generic\TOOLS\SDK_ENG\TESTCASERUNNER\GROUP" mrp="common\generic\tools\sdk_eng\testcaserunner\group\tools_sdk_eng_testcaserunner.mrp" filter="gt"/>
        </component>
        <component name="TOOLBARPANEL">
          <unit unitID="TOOLBARPANEL" name="tools_sdk_eng_toolbarpanel" bldFile="common\generic\TOOLS\SDK_ENG\TOOLBARPANEL\GROUP" mrp="common\generic\tools\sdk_eng\toolbarpanel\group\tools_sdk_eng_toolbarpanel.mrp" filter="gt"/>
        </component>
        <component name="JAVAHELP">
          <unit unitID="JAVAHELP" name="tools_sdk_eng_javahelp" bldFile="common\generic\TOOLS\SDK_ENG\JAVAHELP\GROUP" mrp="common\generic\tools\sdk_eng\javahelp\group\tools_sdk_eng_javahelp.mrp" filter="gt"/>
        </component>
        <component name="LANGCONFIG">
          <unit unitID="LANGCONFIG" name="tools_sdk_eng_langconfig" bldFile="common\generic\TOOLS\SDK_ENG\LANGCONFIG\GROUP" mrp="common\generic\tools\sdk_eng\langconfig\group\tools_sdk_eng_langconfig.mrp" filter="gt"/>
        </component>
        <component name="MBMCODEC">
          <unit unitID="MBMCODEC" name="tools_sdk_eng_mbmcodec" bldFile="common\generic\TOOLS\SDK_ENG\MBMCODEC\GROUP" mrp="common\generic\tools\sdk_eng\mbmcodec\group\tools_sdk_eng_mbmcodec.mrp" filter="gt"/>
        </component>
        <component name="SDKINFO">
          <unit unitID="SDKINFO" name="tools_sdk_eng_sdkinfo" bldFile="common\generic\TOOLS\SDK_ENG\SDKINFO\GROUP" mrp="common\generic\tools\sdk_eng\sdkinfo\group\tools_sdk_eng_sdkinfo.mrp" filter="gt"/>
        </component>
        <component name="JADE">
          <unit unitID="JADE" name="tools_sdk_eng_jade" bldFile="common\generic\TOOLS\SDK_ENG\JADE\GROUP" mrp="common\generic\tools\sdk_eng\jade\group\tools_sdk_eng_jade.mrp" filter="gt"/>
        </component>
        <component name="CSHLPCMP_GUI">
          <unit unitID="CSHLPCMP_GUI" name="tools_sdk_eng_cshlpcmp_gui" bldFile="common\generic\TOOLS\SDK_ENG\CSHLPCMP_GUI\GROUP" mrp="common\generic\tools\sdk_eng\cshlpcmp_gui\group\tools_sdk_eng_cshlpcmp_gui.mrp" filter="gt" priority="1010"/>
        </component>
        <component name="SISAR">
          <unit unitID="SISAR" name="tools_sdk_eng_sisar" bldFile="common\generic\TOOLS\SDK_ENG\SISAR\GROUP" mrp="common\generic\tools\sdk_eng\sisar\group\tools_sdk_eng_sisar.mrp" filter="gt"/>
        </component>
        <component name="SDKPKG-MANAGER">
          <unit unitID="SDKPKG-MANAGER" name="tools_sdk_eng_sdkpkg-manager" bldFile="common\generic\TOOLS\SDK_ENG\SDKPKG-MANAGER\GROUP" mrp="common\generic\tools\sdk_eng\sdkpkg-manager\group\tools_sdk_eng_sdkpkg-manager.mrp" filter="gt"/>
          <package name="product_devkit_pkgdefs" mrp="\product\devkit\product_devkit_pkgdefs.mrp" filter="gt"/>
          <package name="product_techviewexamplesdk_pkgdefs" mrp="\product\techviewexamplesdk\product_techviewexamplesdk_pkgdefs.mrp" filter="gt"/>
        </component>
        <component name="SDKPKG-TOOLS">
          <unit unitID="SDKPKG-TOOLS" name="tools_sdk_eng_sdkpkg-tools" bldFile="common\generic\TOOLS\SDK_ENG\SDKPKG-TOOLS\GROUP" mrp="common\generic\tools\sdk_eng\sdkpkg-tools\group\tools_sdk_eng_sdkpkg-tools.mrp" filter="gt"/>
        </component>
        <component name="EMULATOR_LAUNCHER">
          <unit unitID="EMULATOR_LAUNCHER" name="tools_sdk_eng_emulator_launcher" bldFile="common\generic\TOOLS\SDK_ENG\EMULATOR_LAUNCHER\GROUP" mrp="common\generic\tools\sdk_eng\emulator_launcher\group\tools_sdk_eng_emulator_launcher.mrp" filter="gt"/>
        </component>
        <component name="PKGMGRGUI">
          <unit unitID="PKGMGRGUI" name="tools_sdk_eng_pkgmgrgui" bldFile="common\generic\TOOLS\SDK_ENG\PKGMGRGUI\GROUP" mrp="common\generic\tools\sdk_eng\pkgmgrgui\group\tools_sdk_eng_pkgmgrgui.mrp" filter="gt"/>
        </component>
        <component name="LAUNCH">
          <unit unitID="LAUNCH" name="tools_sdk_eng_launch" bldFile="common\generic\TOOLS\SDK_ENG\LAUNCH\GROUP" mrp="common\generic\tools\sdk_eng\launch\group\tools_sdk_eng_launch.mrp" filter="gt"/>
        </component>
        <component name="TOOLS_STUBS">
          <unit unitID="TOOLS_STUBS" name="tools_sdk_eng_tools_stubs" bldFile="common\generic\TOOLS\SDK_ENG\TOOLS_STUBS\GROUP" mrp="common\generic\tools\sdk_eng\tools_stubs\group\tools_sdk_eng_tools_stubs.mrp" filter="gt"/>
        </component>
        <component name="CWPLUGINS">
          <unit unitID="CWPLUGINS" name="tools_sdk_eng_cwplugins" bldFile="common\generic\TOOLS\SDK_ENG\CWPLUGINS\GROUP" mrp="common\generic\tools\sdk_eng\cwplugins\group\tools_sdk_eng_cwplugins.mrp" filter="gt"/>
        </component>
        <component name="BSPBUILDER">
          <unit unitID="BSPBUILDER" name="tools_bspbuilder" bldFile="common\generic\TOOLS\BSPBUILDER\GROUP" mrp="common\generic\tools\bspbuilder\group\tools_bspbuilder.mrp" filter="gt"/>
        </component>
        <component name="ALP2CSH">
          <unit unitID="ALP2CSH" name="tools_sdk_eng_alp2csh" bldFile="common\generic\TOOLS\SDK_ENG\ALP2CSH\GROUP" mrp="common\generic\tools\sdk_eng\alp2csh\group\tools_sdk_eng_alp2csh.mrp"/>
        </component>
        <component name="CJPEG">
          <unit unitID="CJPEG" name="tools_sdk_eng_cjpeg" bldFile="common\generic\TOOLS\SDK_ENG\CJPEG\GROUP" mrp="common\generic\tools\sdk_eng\cjpeg\group\tools_sdk_eng_cjpeg.mrp"/>
        </component>
        <component name="CSHLPCMP_FRONTEND">
          <unit unitID="CSHLPCMP_FRONTEND" name="tools_sdk_eng_cshlpcmp_frontend" bldFile="common\generic\TOOLS\SDK_ENG\CSHLPCMP_FRONTEND\GROUP" mrp="common\generic\tools\sdk_eng\cshlpcmp_frontend\group\tools_sdk_eng_cshlpcmp_frontend.mrp"/>
          <package name="tools_sdk_eng_cshlpcmp_backend_srconly" mrp="common\generic\tools\sdk_eng\cshlpcmp_backend\group\tools_sdk_eng_cshlpcmp_backend_srconly.mrp"/>
        </component>
        <component name="PERLLIBRARY">
          <unit unitID="PERLLIBRARY" name="tools_sdk_eng_perllibrary" bldFile="common\generic\TOOLS\SDK_ENG\PERLLIBRARY\GROUP" mrp="common\generic\tools\sdk_eng\perllibrary\group\tools_sdk_eng_perllibrary.mrp"/>
        </component>
        <component name="Perl Shared Libraries">
          <unit unitID="PERLSHARED" name="tools_sdk_eng_perl_shared" bldFile="common\generic\tools\sdk_eng\perl_shared\group" mrp="common\generic\tools\sdk_eng\perl_shared\group\tools_sdk_eng_perl_shared.mrp"/>
        </component>
        <component name="RTF2PTML">
          <unit unitID="RTF2PTML" name="tools_sdk_eng_rtf2ptml" bldFile="common\generic\TOOLS\SDK_ENG\RTF2PTML\GROUP" mrp="common\generic\tools\sdk_eng\rtf2ptml\group\tools_sdk_eng_rtf2ptml.mrp"/>
        </component>
        <component name="SPLASH">
          <unit unitID="SPLASH" name="tools_sdk_eng_splash" bldFile="common\generic\TOOLS\SDK_ENG\SPLASH\GROUP" mrp="common\generic\tools\sdk_eng\splash\group\tools_sdk_eng_splash.mrp"/>
        </component>
        <component name="SDK Builder">
          <unit unitID="SDK_BUILDER" name="tools_sdk_eng_sdk_builder" bldFile="common\generic\TOOLS\sdk_eng\sdk_builder\GROUP" mrp="common\generic\tools\sdk_eng\sdk_builder\group\tools_sdk_eng_sdk_builder.mrp"/>
        </component>
      </module>
      <module name="Test Product" level="sdk">
      	<component name="Subsystem Tests">
          <package name="bluetooth_testproduct" mrp="common\generic\bluetooth\latest\testproduct\group\bluetooth_testproduct.mrp"/>
          <package name="multimedia_testproduct" mrp="common\generic\multimedia\testproduct\group\multimedia_testproduct.mrp"/>
	  <package name="messaging_testproduct" mrp="common\generic\messaging\testproduct\group\messaging_testproduct.mrp"/>
	  <package name="syslibs_testproduct" mrp="common\generic\syslibs\testproduct\group\syslibs_testproduct.mrp"/>
	  <package name="comms-infras_testproduct" mrp="common\generic\comms-infras\testproduct\group\comms-infras_testproduct.mrp"/>
	  <package name="graphics_testproduct" mrp="common\generic\graphics\testproduct\group\graphics_testproduct.mrp"/>
         <package name="lbs_testproduct" mrp="common\generic\lbs\test\testproduct\group\lbs_testproduct.mrp"/>
        </component>
      </module>
    </layer>
    <layer name="Kernel Services and Hardware Interface" levels="Hardware-dependent Hardware-independent">
      <logicalset name="Kernel Architecture">
        <module name="ASSP" level="Hardware-dependent">
          <component name="OMAP 1623">
            <!-- No unit? -->
          </component>
        </module>