<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
<!ELEMENT SystemDefinition ( systemModel )>
<!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED
>
<!-- all paths are relative to the environment variable specified by the root attribute, or SOURCEROOT if not.  -->

<!-- System Model Section of DTD -->
<!ELEMENT systemModel (layer+)>

<!ELEMENT layer (block* | collection*)*>
<!-- Kernel Services, Base Services, OS Services, Etc -->
<!ATTLIST layer
  name CDATA #REQUIRED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
>

<!ELEMENT block (subblock* | collection*)*>
 <!-- Generic OS services, Comms Services, etc -->
<!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
>

<!ELEMENT subblock (collection)*>
<!-- Cellular Baseband Services, Networking Services, etc -->
<!ATTLIST subblock
  name CDATA #REQUIRED
>

<!ELEMENT collection (component)*>
<!-- Screen Driver, Content Handling, etc -->
<!ATTLIST collection
  name CDATA #REQUIRED
  level NMTOKEN #IMPLIED
>

<!ELEMENT component (unit)*>
<!-- contains units or is a  package or prebuilt -->
<!ATTLIST component
  name CDATA #REQUIRED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
>

<!ELEMENT unit EMPTY >
<!-- must be buildable (bld.inf) -->
<!-- bldFile  may someday be removed in favour of mrp -->
<!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED
>
]>
<SystemDefinition name="MCL" schema="2.0.0">
  <systemModel>
    <layer name="Tools and Utils and SDKENG" levels="SDK tools test">
      <block name="System Build and Test">
        <collection name="Build System Tools" level="tools">
          <component name="BUILDSYSTEMTOOLS">
            <unit bldFile="common/generic/tools/build/group" mrp="common/generic/tools/build/group/tools_build.mrp"/>
          </component>
          <component name="GT Techview Baseline">
            <unit mrp="common/generic/tools/cbr/mrpfiles/gt_techview_baseline.mrp"/>
            <!-- DEF087736 This is needed for generating export tables but shouldn't appear otherwise it is included in techview and gt
		     <package name="gt_only_baseline" mrp="common/generic/tools/cbr/mrpfiles/gt_only_baseline.mrp"/> -->
          </component>
          <component name="Cedar Utils">
            <unit mrp="cedar/generic/utils/tools_utils_cedar.mrp"/>
          </component>
          <component name="Common Utils">
            <unit mrp="common/generic/utils/tools_utils_common.mrp"/>
          </component>
          <component name="Additional Utils">
            <unit mrp="common/generic/tools/cbr/mrpfiles/additional_unknown_cedar.mrp"/>
          </component>
        </collection>
        <collection name="Tools and Utils" level="tools">
          <component name="CTS Functionality Checkers">
            <unit mrp="common/testtools/cts/FunctionalityCheckers/Group/testtools_cts_functionalitycheckers.mrp"/>
          </component>
          <component name="BURTESTSERVER">
            <unit bldFile="common/testtools/burtestserver/Group" mrp="common/testtools/burtestserver/Group/testtools_burtestserver.mrp"/>
          </component>
          <component name="CBRTOOLS" filter="gt">
            <unit bldFile="common/generic/tools/cbr/tools/group" mrp="common/generic/tools/cbr/tools/group/tools_cbr_tools.mrp"/>
          </component>
          <component name="CBRPRF">
            <unit bldFile="common/generic/tools/cbr/prf/group" mrp="common/generic/tools/cbr/prf/group/tools_cbr_prf.mrp"/>
          </component>
          <component name="CDB">
            <unit bldFile="common/testtools/cdb/group" mrp="common/testtools/cdb/group/testtools_cdb.mrp"/>
          </component>
          <component name="DEPCHECK">
            <unit bldFile="common/generic/tools/depcheck" mrp="common/generic/tools/depcheck/tools_depcheck.mrp"/>
          </component>
          <component name="Dependency Modeller" introduced="9.2" class="test PC">
            <unit bldFile="common/generic/tools/depmodel/group" mrp="common/generic/tools/depmodel/tools_depmodel.mrp"/>
          </component>
          <component name="E32 Tools" class="PC">
            <unit bldFile="cedar/generic/tools/e32tools/group" mrp="cedar/generic/tools/e32tools/group/tools_e32tools.mrp"/>
          </component>
          <component name="E32 Perl Tools" class="PC">
            <unit mrp="cedar/generic/tools/e32toolp/group/tools_e32toolp.mrp"/>
          </component>
          <component name="EVALID">
            <unit bldFile="common/generic/tools/host_utilities/evalid" mrp="common/generic/tools/host_utilities/evalid/tools_evalid.mrp"/>
          </component>
          <component name="KITCOMPARATOR">
            <unit bldFile="common/testtools/cts/kitcomparator/group" mrp="common/testtools/cts/kitcomparator/group/testtools_cts_kitcomparator.mrp"/>
          </component>
          <component name="SYSTEMTEST_OS" filter="techview">
            <unit bldFile="common/generic/SystemTest/Symbian/Group" mrp="common/generic/SystemTest/Symbian/Group/systemtest_os.mrp"/>
          </component>
		  <component name="SYSTEMTEST_TOOLS" filter="techview">
            <unit bldFile="common/generic/SystemTest/Tools/Group" mrp="common/generic/SystemTest/Tools/Group/systemtest_tools.mrp"/>
          </component>
          <component name="LEAVESCAN">
            <unit bldFile="common/testtools/leavescan/group" mrp="common/testtools/leavescan/group/testtools_leavescan.mrp"/>
          </component>
          <component name="PROGRAMCHECKER">
            <unit bldFile="common/testtools/programchecker/group" mrp="common/testtools/programchecker/group/testtools_programchecker.mrp"/>
          </component>
          <component name="RCOMP">
            <unit bldFile="common/generic/tools/rcomp/group" mrp="common/generic/tools/rcomp/group/tools_rcomp.mrp"/>
          </component>
          <component name="Redistribution" filter="gt">
            <unit bldFile="common/generic/tools/redistribution" mrp="common/generic/tools/redistribution/tools_redistribution_common.mrp"/>
          </component>
          <component name="WinC Redistribution">
            <unit mrp="cedar/generic/tools/redistribution/tools_redistribution_winc.mrp"/>
          </component>
          <component name="Additional Redistribution">
            <unit mrp="common/generic/tools/redistribution/additional_tools.mrp"/>
          </component>
          <component name="ROMKIT_EKA2">
            <unit bldFile="cedar/generic/tools/romkit/group" mrp="cedar/generic/tools/romkit/group/tools_romkit.mrp"/>
          </component>
          <component name="MIGRATIONTOOL">
            <unit bldFile="common/testtools/migrationtool/group" mrp="common/testtools/migrationtool/group/testtools_migrationtool.mrp"/>
          </component>
          <component name="TESTDRIVER">
            <unit bldFile="common/testtools/TestDriver/Group" mrp="common/testtools/TestDriver/Group/testtools_testdriver.mrp"/>
          </component>
          <component name="S60 Compatibility Headers" filter="gt">
            <unit version="9.5" bldFile="common/generic/tools/s60_header_compat/group95" mrp="common/generic/tools/s60_header_compat/group95/tools_s60_header_compat95.mrp"/>
            <unit version="Future" bldFile="common/generic/tools/s60_header_compat/groupfuture" mrp="common/generic/tools/s60_header_compat/groupfuture/tools_s60_header_compatfuture.mrp"/>
          </component>
          <component name="SMOKETEST" filter="gt">
            <unit bldFile="common/testtools/smoketest/Group" mrp="common/testtools/smoketest/Group/testtools_smoketest.mrp"/>
          </component>
          <component name="Stat API" filter="gt">
            <unit bldFile="common/testtools/stat/device/source/statapi/console" mrp="common/testtools/stat/device/group/testtools_stat_device_gt.mrp"/>
          </component>
          <component name="Stat Source" contract="Symbian_Affiliate" filter="gt">
            <unit mrp="common/testtools/stat/group/testtools_stat_common_source.mrp"/>
          </component>
          <component name="STAT_DESKTOP" contract="Symbian_Affiliate" filter="gt">
            <unit bldFile="common/testtools/stat/desktop/group" mrp="common/testtools/stat/desktop/group/testtools_stat_desktop.mrp"/>
          </component>
          <component name="TESTEXECUTE">
            <unit bldFile="common/testtools/testexecute/Group" mrp="common/testtools/testexecute/Group/tools_testexecute.mrp"/>
          </component>
          <component name="SYSTEMMONITOR" introduced="8.0">
            <unit bldFile="common/testtools/systemmonitor/group" mrp="common/testtools/systemmonitor/group/testtools_systemmonitor.mrp"/>
          </component>
          <component name="Test Tools Desktop" filter="gt">
            <unit bldFile="common/testtools/desktop/group" mrp="common/testtools/desktop/group/testtools_desktop.mrp"/>
          </component>
          <component name="Wintunnel">
            <unit mrp="common/testtools/wintunnel/group/testtools_WinTunnel_srconly.mrp"/>
          </component>
          <component name="Use Case Controller">
            <unit bldFile="common/testtools/ucc/BuildScripts/group" mrp="common/testtools/ucc/BuildScripts/group/testtools_ucc.mrp"/>
          </component>
          <component name="CINIDATA">
            <unit bldFile="common/generic/tools/cinidata" mrp="common/generic/tools/cinidata/tools_cinidata.mrp"/>
          </component>
          <component name="AUTOTEST">
            <unit bldFile="common/generic/tools/autotest/group" mrp="common/generic/tools/autotest/group/tools_autotest.mrp"/>
          </component>
          <component name="TESTCONFIGFILEPARSER">
            <unit bldFile="common/generic/tools/testconfigfileparser/group" mrp="common/generic/tools/testconfigfileparser/group/tools_testconfigfileparser.mrp"/>
          </component>
          <component name="KITSETUPAPP" filter="gt">
            <unit bldFile="common/generic/tools/devkits/kitsetupapp/group" mrp="common/generic/tools/devkits/kitsetupapp/group/tools_devkits_kitsetupapp.mrp" priority="1020"/>
          </component>
          <component name="NAVIGATION_PAGES">
            <unit mrp="common/generic/tools/sdk_eng/NavigationPages/tools_sdk_eng_NavigationPages.mrp"/>
          </component>
          <component name="PRODUCTINSTALLER" filter="gt">
            <unit bldFile="common/generic/tools/custkits/productinstaller/group" mrp="common/generic/tools/custkits/productinstaller/group/tools_custkits_productinstaller.mrp"/>
          </component>
          <component name="REDISTRIBUTION_WINC_EKA2">
            <unit bldFile="cedar/generic/tools/redistribution" mrp="cedar/generic/tools/redistribution/tools_redistribution_cedar.mrp"/>
          </component>
          <component name="CAPTOOLS">
            <unit bldFile="common/testtools/captools/group" mrp="common/testtools/captools/group/testtools_captools.mrp"/>
          </component>
          <component name="STLPORT">
            <unit bldFile="common/generic/tools/stlport/group" mrp="common/generic/tools/stlport/group/tools_stlport.mrp"/>
          </component>
        </collection>
        <collection name="Developer Library" level="test">
          <component name="Developer Library Tools" class="placeholder">
            <!-- placeholder for  mrp="common/developerlibrary/tools/developerlibrary_tools.mrp" -->
          </component>
          <component name="Developer Library Help" class="doc">
            <unit version="9.5" bldFile="common/developerlibrary/group/devlib95" mrp="common/developerlibrary/group/devlib95/developerlibrary_doc_html.mrp"/>
          </component>
          <component name="Developer Library Source" filter="gt" class="doc">
            <unit bldFile="common/developerlibrary/securitysupplement/doc_source" mrp="common/developerlibrary/developerlibrary_doc_source.mrp"/>
          </component>
          <component name="Developer Library HTML" class="doc">
            <unit mrp="common/developerlibrary/group/shared/developerlibrary_doc_plain_html.mrp"/>
          </component>
          <component name="System Documentation" class="doc">
            <unit mrp="common/system/group/system.mrp"/>
          </component>
          <component name="Tools Documentation" class="doc">
            <unit mrp="cedar/generic/tools/documentation/tools_documentation.mrp"/>
          </component>
        </collection>
        <collection name="SDKENG" level="SDK">
          <component name="RUNPERL" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/runperl/group" mrp="common/generic/tools/sdk_eng/runperl/group/tools_sdk_eng_runperl.mrp"/>
          </component>
          <component name="BUILD-TOOLS" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/build-tools/group" mrp="common/generic/tools/sdk_eng/build-tools/group/tools_sdk_eng_build-tools.mrp"/>
          </component>
          <component name="JAVALIBRARY" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/javalibrary/group" mrp="common/generic/tools/sdk_eng/javalibrary/group/tools_sdk_eng_javalibrary.mrp"/>
          </component>
          <component name="ASSERTION" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/assertion/group" mrp="common/generic/tools/sdk_eng/assertion/group/tools_sdk_eng_assertion.mrp"/>
          </component>
          <component name="ENUM" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/enum/group" mrp="common/generic/tools/sdk_eng/enum/group/tools_sdk_eng_enum.mrp"/>
          </component>
          <component name="LOGGER" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/logger/group" mrp="common/generic/tools/sdk_eng/logger/group/tools_sdk_eng_logger.mrp"/>
          </component>
          <component name="FILESYS" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/filesys/group" mrp="common/generic/tools/sdk_eng/filesys/group/tools_sdk_eng_filesys.mrp"/>
          </component>
          <component name="ENVVAR" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/envvar/group" mrp="common/generic/tools/sdk_eng/envvar/group/tools_sdk_eng_envvar.mrp"/>
          </component>
          <component name="INSTALLUTILS" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/installutils/group" mrp="common/generic/tools/sdk_eng/installutils/group/tools_sdk_eng_installutils.mrp"/>
          </component>
          <component name="MNEMONICFIX" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/mnemonicfix/group" mrp="common/generic/tools/sdk_eng/mnemonicfix/group/tools_sdk_eng_mnemonicfix.mrp"/>
          </component>
          <component name="PATHBROWSER" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/pathbrowser/group" mrp="common/generic/tools/sdk_eng/pathbrowser/group/tools_sdk_eng_pathbrowser.mrp"/>
          </component>
          <component name="SHELLEXEC" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/shellexec/group" mrp="common/generic/tools/sdk_eng/shellexec/group/tools_sdk_eng_shellexec.mrp"/>
          </component>
          <component name="SWINGWORKER" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/swingworker/group" mrp="common/generic/tools/sdk_eng/swingworker/group/tools_sdk_eng_swingworker.mrp"/>
          </component>
          <component name="TESTCASERUNNER" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/testcaserunner/group" mrp="common/generic/tools/sdk_eng/testcaserunner/group/tools_sdk_eng_testcaserunner.mrp"/>
          </component>
          <component name="TOOLBARPANEL" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/toolbarpanel/group" mrp="common/generic/tools/sdk_eng/toolbarpanel/group/tools_sdk_eng_toolbarpanel.mrp"/>
          </component>
          <component name="JAVAHELP" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/javahelp/group" mrp="common/generic/tools/sdk_eng/javahelp/group/tools_sdk_eng_javahelp.mrp"/>
          </component>
          <component name="LANGCONFIG" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/langconfig/group" mrp="common/generic/tools/sdk_eng/langconfig/group/tools_sdk_eng_langconfig.mrp"/>
          </component>
          <component name="MBMCODEC" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/mbmcodec/group" mrp="common/generic/tools/sdk_eng/mbmcodec/group/tools_sdk_eng_mbmcodec.mrp"/>
          </component>
          <component name="SDKINFO" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/sdkinfo/group" mrp="common/generic/tools/sdk_eng/sdkinfo/group/tools_sdk_eng_sdkinfo.mrp"/>
          </component>
          <component name="JADE" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/jade/group" mrp="common/generic/tools/sdk_eng/jade/group/tools_sdk_eng_jade.mrp"/>
          </component>
          <component name="CSHLPCMP_GUI" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/cshlpcmp_gui/group" mrp="common/generic/tools/sdk_eng/cshlpcmp_gui/group/tools_sdk_eng_cshlpcmp_gui.mrp" priority="1010"/>
          </component>
          <component name="SDK Package Manager" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/sdkpkg-manager/group" mrp="common/generic/tools/sdk_eng/sdkpkg-manager/group/tools_sdk_eng_sdkpkg-manager.mrp"/>
          </component>
          <component name="Example Package Defs" filter="gt">
            <unit mrp="/product/TechviewExampleSDK/product_TechViewExampleSDK_pkgdefs.mrp"/>
          </component>
          <component name="SDKPKG-TOOLS" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/sdkpkg-tools/group" mrp="common/generic/tools/sdk_eng/sdkpkg-tools/group/tools_sdk_eng_sdkpkg-tools.mrp"/>
          </component>
          <component name="EMULATOR_LAUNCHER" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/emulator_launcher/group" mrp="common/generic/tools/sdk_eng/emulator_launcher/group/tools_sdk_eng_emulator_launcher.mrp"/>
          </component>
          <component name="PKGMGRGUI" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/pkgmgrgui/group" mrp="common/generic/tools/sdk_eng/pkgmgrgui/group/tools_sdk_eng_pkgmgrgui.mrp"/>
          </component>
          <component name="LAUNCH" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/launch/group" mrp="common/generic/tools/sdk_eng/launch/group/tools_sdk_eng_launch.mrp"/>
          </component>
          <component name="TOOLS_STUBS" filter="gt">
            <unit bldFile="common/generic/tools/sdk_eng/tools_stubs/group" mrp="common/generic/tools/sdk_eng/tools_stubs/group/tools_sdk_eng_tools_stubs.mrp"/>
          </component>
          <component name="BSPBUILDER" filter="gt">
            <unit bldFile="common/generic/tools/bspbuilder/group" mrp="common/generic/tools/bspbuilder/group/tools_bspbuilder.mrp"/>
          </component>
          <component name="ALP2CSH">
            <unit bldFile="common/generic/tools/sdk_eng/alp2csh/group" mrp="common/generic/tools/sdk_eng/alp2csh/group/tools_sdk_eng_alp2csh.mrp"/>
          </component>
          <component name="CJPEG">
            <unit bldFile="common/generic/tools/sdk_eng/cjpeg/group" mrp="common/generic/tools/sdk_eng/cjpeg/group/tools_sdk_eng_cjpeg.mrp"/>
          </component>
          <component name="CSHLPCMP Frontend">
            <unit bldFile="common/generic/tools/sdk_eng/cshlpcmp_frontend/group" mrp="common/generic/tools/sdk_eng/cshlpcmp_frontend/group/tools_sdk_eng_cshlpcmp_frontend.mrp"/>
          </component>
          <component name="CSHLPCMP Backend">
            <unit mrp="common/generic/tools/sdk_eng/cshlpcmp_backend/group/tools_sdk_eng_cshlpcmp_backend_srconly.mrp"/>
          </component>
          <component name="PERLLIBRARY">
            <unit bldFile="common/generic/tools/sdk_eng/perllibrary/group" mrp="common/generic/tools/sdk_eng/perllibrary/group/tools_sdk_eng_perllibrary.mrp"/>
          </component>
          <component name="Perl Shared Libraries">
            <unit bldFile="common/generic/tools/sdk_eng/perl_shared/group" mrp="common/generic/tools/sdk_eng/perl_shared/group/tools_sdk_eng_perl_shared.mrp"/>
          </component>
          <component name="RTF2PTML">
            <unit bldFile="common/generic/tools/sdk_eng/rtf2ptml/group" mrp="common/generic/tools/sdk_eng/rtf2ptml/group/tools_sdk_eng_rtf2ptml.mrp"/>
          </component>
          <component name="SPLASH">
            <unit bldFile="common/generic/tools/sdk_eng/splash/group" mrp="common/generic/tools/sdk_eng/splash/group/tools_sdk_eng_splash.mrp"/>
          </component>
          <component name="SDK Builder">
            <unit bldFile="common/generic/tools/sdk_eng/SDK_Builder/group" mrp="common/generic/tools/sdk_eng/SDK_Builder/group/tools_sdk_eng_sdk_builder.mrp"/>
          </component>
        </collection>
        <collection name="Test Product" level="test">
          <component name="Bluetooth Test Product" introduced="9.2" class="test">
            <unit mrp="common/generic/bluetooth/latest/testproduct/group/bluetooth_testproduct.mrp"/>
          </component>
          <component name="Multimedia Test Product" class="test" introduced="8.1">
            <unit mrp="common/generic/multimedia/testproduct/group/multimedia_testproduct.mrp"/>
          </component>
          <component name="Syslibs Test Product" class="test" introduced="9.2">
            <unit mrp="common/generic/syslibs/testproduct/group/syslibs_testproduct.mrp"/>
          </component>
          <component name="Comms Infrastructure Test Product" introduced="9.2" class="test">
            <unit mrp="common/generic/comms-infras/testproduct/group/comms-infras_testproduct.mrp"/>
          </component>
          <component name="Graphics Test Product" class="test" introduced="9.2">
            <unit mrp="common/generic/graphics/testproduct/group/graphics_testproduct.mrp"/>
          </component>
        </collection>
      </block>
    </layer>
    <layer name="Hardware" levels="Hardware-dependent">
      <block name="Board Support Packages" level="Hardware-dependent">
        <collection name="Emulator">
          <component name="Emulator BSP" contract="Symbian_SD4C">
            <unit bldFile="cedar/generic/base/emulator/wins" mrp="cedar/generic/base/emulator/wins/base_wins.mrp"/>
          </component>
          <component name="Unistore2 Emulator Support" contract="NAND_Flash_XSR_Unistore_2_Other_Portions" filter="gt" introduced="9.4">
            <unit bldFile="cedar/generic/base/emulator/wins_restricted/unistore2" mrp="cedar/generic/base/emulator/wins_restricted/unistore2/base_wins_unistore2.mrp"/>
          </component>
        </collection>
        <collection name="Integrator BSP">
          <component name="Integrator Motherboard" introduced="8.1b">
            <unit bldFile="cedar/generic/base/integrator/integratorap" mrp="cedar/generic/base/integrator/integratorap/base_integrator_integratorap.mrp"/>
          </component>
          <component name="Integrator Core Modules">
            <unit bldFile="cedar/generic/base/integrator/core" mrp="cedar/generic/base/integrator/core/base_integrator_core_8.1b.mrp"/>
          </component>
          <component name="Integrator ARM920 Core Module" introduced="8.1b">
            <unit bldFile="cedar/generic/base/integrator/core/cm920" mrp="cedar/generic/base/integrator/core/cm920/base_integrator_core_cm920.mrp"/>
          </component>
          <component name="Integrator ARM1136 Core Module">
            <unit bldFile="cedar/generic/base/integrator/core/cm1136" mrp="cedar/generic/base/integrator/core/cm1136/base_integrator_core_cm1136.mrp"/>
          </component>
          <component name="Integrator XX600 Logic Module" introduced="8.1b">
            <unit bldFile="cedar/generic/base/integrator/logic/lmxx600" mrp="cedar/generic/base/integrator/logic/lmxx600/base_integrator_logic_lmxx600.mrp"/>
          </component>
          <component name="Integrator SSR NAND Logic Module" introduced="8.1b">
            <unit bldFile="cedar/generic/base/integrator/logic/lmnand" mrp="cedar/generic/base/integrator/logic/lmnand/base_integrator_logic_lmnand.mrp"/>
          </component>
          <component name="Integrator Panasonic Logic Module" contract="SD_Card_PSL" introduced="8.1">
            <unit mrp="cedar/generic/base/integrator/logic/lm_pana/base_integrator_logic_lm_pana.mrp"/>
          </component>
          <component name="Integrator Unistore2 NAND Logic Module" contract="NAND_Flash_XSR_Unistore_2_Other_Portions" filter="gt" introduced="8.1">
            <unit bldFile="cedar/generic/base/integrator/logic/lmnand2" mrp="cedar/generic/base/integrator/logic/lmnand2/base_integrator_logic_lmnand2.mrp"/>
          </component>
        </collection>
        <collection name="OMAP H2">
          <component name="OMAP H2 BSP" introduced="9.0">
            <unit bldFile="cedar/generic/base/omap/h2" mrp="cedar/generic/base/omap/h2/base_omaph2.mrp"/>
          </component>
          <component name="OMAP H2 Unistore2" contract="NAND_Flash_XSR_Unistore_2_Other_Portions" filter="gt" introduced="9.1">
            <unit bldFile="cedar/generic/base/omap/h2_restricted/unistore2" mrp="cedar/generic/base/omap/h2_restricted/unistore2/base_h2_unistore2.mrp"/>
          </component>
          <component name="OMAP H2 SDIO" filter="gt" introduced="9.2">
            <unit bldFile="cedar/generic/base/omap/h2_restricted/sdio" mrp="cedar/generic/base/omap/h2_restricted/sdio/base_h2_sdio.mrp"/>
          </component>
        </collection>
        <collection name="OMAP H4">
          <component name="OMAP H4 BSP">
            <unit bldFile="cedar/generic/base/omap_hrp/h4" mrp="cedar/generic/base/omap_hrp/h4/base_omaph4hrp.mrp"/>
          </component>
          <component name="H4 Boot Loader" introduced="9.1">
            <unit mrp="cedar/generic/base/omap_hrp/h4_bootloader/base_omaph4hrp_bootldr.mrp" bldFile="cedar/generic/base/omap_hrp/h4_bootloader"/>
          </component>
          <component name="OMAP H4 Mini Environment Boot Loader" introduced="9.2">
            <unit mrp="cedar/generic/base/omap_hrp/h4_mebootloader/base_omaph4hrp_mebootldr.mrp" bldFile="cedar/generic/base/omap_hrp/h4_mebootloader"/>
          </component>
          <component name="OMAP H4 Unistore2" contract="NAND_Flash_XSR_Unistore_2_Other_Portions" filter="gt" introduced="9.2">
            <unit bldFile="cedar/generic/base/omap_hrp/h4_restricted/unistore2" mrp="cedar/generic/base/omap_hrp/h4_restricted/unistore2/base_omaph4hrp_unistore2.mrp"/>
          </component>
          <component name="OMAP H4 SDIO" filter="gt" introduced="9.2">
            <unit bldFile="cedar/generic/base/omap_hrp/h4_restricted/sdio" mrp="cedar/generic/base/omap_hrp/h4_restricted/sdio/base_omaph4hrp_sdio.mrp"/>
          </component>
        </collection>
        <collection name="OMAP3 Variants">
          <component name="TI OMAP3 BSP" introduced="9.6">
            <unit bldFile="cedar/generic/base/tiomap3/variant/34xx_sdp" mrp="cedar/generic/base/tiomap3/base_tiomap3.mrp"/>
          </component>
          <component name="TI OMAP3 Unistore2" filter="gt" introduced="9.6">
            <unit bldFile="cedar/generic/base/tiomap3/variant/34xx_sdp_restricted/unistore2" mrp="cedar/generic/base/tiomap3/base_tiomap3_unistore2.mrp"/>
          </component>
        </collection>
        <collection name="NaviEngine Baseport">
          <component name="NaviEngine BSP" introduced="9.6" filter="gt">
            <unit version="Source_Only" mrp="cedar/generic/base/bsp/hwip_nec_naviengine/base_naviengine_source_only.mrp"/>
            <unit version="Built" bldFile="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb" mrp="cedar/generic/base/bsp/hwip_nec_naviengine/base_naviengine.mrp"/>
          </component>
          <component name="NaviEngine BSP flexible" introduced="9.6" filter="gt">
            <unit version="Built" bldFile="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb/flexible" mrp="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb/flexible/base_naviengine_flexible.mrp"/>
            <unit version="Source_Only" mrp="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb/flexible/base_naviengine_flexible_source_only.mrp"/>
          </component>
          <component name="NaviEngine Boot Loader" introduced="9.6" filter="gt">
            <unit version="Built" bldFile="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb_bootloader" mrp="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb_bootloader/base_ne1_tb_bootldr.mrp"/>
            <unit version="Source_Only" mrp="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb_bootloader/base_ne1_tb_bootldr_source_only.mrp"/>
          </component>
					<component name="NaviEngine Unistore2" filter="gt" introduced="9.6" class="placeholder">
					  <!-- PLACEHOLDER="DS.1419"
						<unit bldFile="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb_restricted/unistore2" mrp="cedar/generic/base/bsp/hwip_nec_naviengine/ne1_tb_restricted/unistore2/base_nec_naviengine_unistore2.mrp"/> 
						-->
					</component>
        </collection>
      </block>
    </layer>
    <layer name="Kernel Services">
      <block name="Kernel and Hardware Services" levels="generic specific user">
        <collection name="Kernel Architecture" level="specific">
          <component name="Kernel Architecture 2" introduced="8.0">
            <unit bldFile="cedar/generic/base/e32" mrp="cedar/generic/base/e32/base_e32.mrp"/>